### ISSUE TITLE
Switching view without using the sidebar

### ISSUE THREAD

**Issue by Big-Iron-Cheems** [MammaMiaDev/avaloniaui-the-series#7]
Hello, I was trying to implement a way to switch from a given view to another based on an event.
In this case, I wanted to click a button in the `HomePageView`, which would load the `ButtonPageView`.

Some snippets for context:
```C#
public partial class HomePageView : UserControl {
    public HomePageView() {
        InitializeComponent();
    }

   /// Duble clicked one of the buttons in this view
    private void GameSelected(object? sender, TappedEventArgs e) {
        if (DataContext is HomePageViewModel viewModel) viewModel.SwitchToButtonsTab();
    }
}
```
```C#
public partial class HomePageViewModel : ViewModelBase {
    [ObservableProperty] private Game? _selectedGame;

    public void SwitchToButtonsTab() {
        var mainViewModel = Ioc.Default.GetService<MainViewModel>();
        var buttonPageViewModel = Ioc.Default.GetService<ButtonPageViewModel>();

        if (mainViewModel != null && buttonPageViewModel != null) {
            buttonPageViewModel.SelectedGame = SelectedGame;
            mainViewModel.CurrentPage = buttonPageViewModel;
            mainViewModel.SelectedListItem =
                mainViewModel.Items.FirstOrDefault(item => item.ModelType == typeof(ButtonPageViewModel));
        }
    }
}
```
```C#
public partial class ButtonPageViewModel : ViewModelBase {
    [ObservableProperty] private Game? _selectedGame;
    
    public ButtonPageViewModel() {
        Console.WriteLine("ButtonPageViewModel initialized");
    }
	
	/// Log when the property changes
    partial void OnSelectedGameChanged(Game? value) {
        Console.WriteLine($"Selected game changed to {value?.Name}");
    }
}
```

My issue is, that after the view switches, this text in `ButtonPageView.axaml` is correct for a couple of frames.
```axaml
<TextBlock Text="{Binding SelectedGame.Name, FallbackValue='NONE'}" />
```

Via the logs, I see the following messages:
```log
Pointer pressed on Game { Name = 20XX }
ButtonPageViewModel initialized
Selected game changed to 20XX
ButtonPageViewModel initialized
```

I am by no means experienced in making GUI apps or using the DI framework that this project showcases, and can't seem to figure out why this happens.

In general, I would like to know what's the most straightforward way, using this project as a base, to switch fom one view to another, without clicking the sidebar entries.

**Comment by MammaMiaDev** [comment]
Hey @Big-Iron-Cheems!
After a quick look, i think the issue might be in here:
```c#
mainViewModel.CurrentPage = buttonPageViewModel;
mainViewModel.SelectedListItem =
    mainViewModel.Items.FirstOrDefault(item => item.ModelType == typeof(ButtonPageViewModel));
```
both of those lines are triggering the "navigation", creating the same view twice (therefore the two `ButtonPageViewModel initialized` log lines). The first time the `TextBlock` has the correct text, the second time it is initialized with the default value.

Not really sure of what's the best way to switch view in this case, but if I read "events" I can't help but thinking about the MVVM [Messenger](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/messenger) feature.

> The `IMessenger` interface is a contract for types that can be used to exchange messages between different objects. This can be useful to decouple different modules of an application without having to keep strong references to types being referenced

It might work more or less like this:
- the `GameSelected` button sends a message when clicked (see how I do it in the login page [here](https://github.com/MammaMiaDev/avaloniaui-the-series/blob/main/src/AvaloniaMiaDev/ViewModels/SplitViewPane/LoginPageViewModel.cs#L52) for instance)
- the `MainViewModel` is subscribed to your specific `GameSelectedEvent` (another example [here](https://github.com/MammaMiaDev/avaloniaui-the-series/blob/main/src/AvaloniaMiaDev/ViewModels/MainViewModel.cs#L20-L23)) and sets the `CurrentPage` to your `buttonPageViewModel` with the correct `SelectedGame`

This should work in theory. Hope it helps.

PS
You can avoid creating a method inside the `HomePageView`
```c#
private void GameSelected(object? sender, TappedEventArgs e) {
    if (DataContext is HomePageViewModel viewModel) viewModel.SwitchToButtonsTab();
}
```
but instead, to fully leverage the MVVM pattern, you can decorate `SwitchToButtonsTab` with a `[RelayCommand]` attribute and bind it directly to the `GameSelected` button. An example is the [TriggerPane](https://github.com/MammaMiaDev/avaloniaui-the-series/blob/main/src/AvaloniaMiaDev/ViewModels/MainViewModel.cs#L69-L73) method, which has a binding with the [hamburger button](https://github.com/MammaMiaDev/avaloniaui-the-series/blob/main/src/AvaloniaMiaDev/Views/MainView.axaml#L30) inside the sidebar.

PPS
I guess you're setting the `SelectedListItem` after the `CurrentPage` as well in order to have the item being highlighted inside the sidebar. Problem is that, by setting the `SelectedListItem`, you also trigger the [OnSelectedListItemChanged](https://github.com/MammaMiaDev/avaloniaui-the-series/blob/main/src/AvaloniaMiaDev/ViewModels/MainViewModel.cs#L54) method, which is setting the `CurrentPage` with a fresh ViewModel (with default values). I'm not proud of that method honestly 😆 you probably need to tweak it if you want the item to be highlighted without resetting the current view model.

**Comment by Big-Iron-Cheems** [comment]
Thanks for the comprehensive response 🙏, I will try and tinker with these suggestions and see where it leads me.
`IMessenger` does seem like the perfect candidate for these things.

**Comment by Big-Iron-Cheems** [comment]
Update: 
seems like I managed to make this work using `IMessenger` (though for some reason it only works if I use `WeakReferenceMessenger.Default` instead of `new WeakReferenceMessenger()` when creating my ViewModels.

Thanks again for your suggestions.
